sudo: required
services:
  - docker
before_install:
  - docker build -t jatin/dashboard -f Dockerfile .
after_success:
  - docker login --username $HEROKU_DOCKER_USERNAME --password $HEROKU_AUTH_PASSWORD registry.heroku.com
  - docker tag dashboard-app:latest registry.heroku.com/frontend-1-staging/web
  - docker push registry.heroku.com/frontend-1-staging/web;
