sudo: required
services:
  - docker
before_install:
  - docker build -t jatin/dashboard -f Dockerfile .
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: "$HEROKU_AUTH_PASSWORD"
  app: frontend-1-staging
