sudo: required
services:
  - docker
before_install:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh #install heroku
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD registry.heroku.com
script:
  - docker build -t jatin/dashboard -f Dockerfile .
  - docker tag jatin/dashboard registry.heroku.com/$HEROKU_APP/web
deploy:
  provider: script
  script: docker push jatin/dashboard;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master
